### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dzek69** [dzek69/ts-library-template#2]
- [x] remove flow version in eslintrc
- [ ] update some overrides in the eslint rules
- [x] compile to react-jsx
- [x] use base tsconfig and extend

**Comment by dzek69** [comment]
- babel.config.cjs to .npm ignore instead of *.js
